spring:
  main:
#    web-application-type: none
    # NOTE: You must disable the banner and the console logging to allow the STDIO transport to work !!!
    banner-mode: off
  ai:
    mcp:
      server:
        name: my-weather-server
        version: 0.0.1
        protocol: STATELESS # webmvc 추가

logging:
#  pattern:
#    console:
  file:
    name: ./log/spring-ai-starter-mcp-server-webmvc.log